server:
  port: 8084
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/message-management
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update