server:
  port: 8080
catalog:
  host: http://localhost
  port: 8081
  url: ${catalog.host}:${catalog.port}
customer-management:
  host: http://localhost
  port: 8082
  url: ${customer-management.host}:${customer-management.port}
favourite-item-management:
  host: http://localhost
  port: 8083
  url: ${favourite-item-management.host}:${favourite-item-management.port}