server:
  port: ${PROCESSOR_SERVER_PORT:8080}
catalog:
  host: ${CATALOG_HOST:http://localhost}
  port: ${CATALOG_PORT:8081}
  url: ${catalog.host}:${catalog.port}
customer-management:
  host: ${CUSTOMER_MANAGEMENT_HOST:http://localhost}
  port: ${CUSTOMER_MANAGEMENT_PORT:8082}
  url: ${customer-management.host}:${customer-management.port}
favourite-item-management:
  host: ${FAVOURITE_ITEM_MANAGEMENT_HOST:http://localhost}
  port: ${FAVOURITE_ITEM_MANAGEMENT_PORT:8083}
  url: ${favourite-item-management.host}:${favourite-item-management.port}