server:
  port: 8080
catalog:
  host: http://localhost
  port: 8081
  url: ${catalog.host}:${catalog.port}
customer-management:
  host: http://localhost
  port: 8082
  url: ${customer-management.host}:${customer-management.port}
favourite-item-management:
  host: http://localhost
  port: 8083
  url: ${favourite-item-management.host}:${favourite-item-management.port}
logging:
  file: logs/production_app.log
  pattern:
    file: "%d %-5level [%thread] %logger{0}: %msg%n"
    console: "%d %-5level [%thread] %logger{0}: %msg%n"
  level:
    com.bsuir.sdtt: DEBUG