server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/favourite-item-management
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
logging:
  file: logs/production_app.log
  pattern:
    file: "%d %-5level [%thread] %logger{0}: %msg%n"
    console: "%d %-5level [%thread] %logger{0}: %msg%n"
  level:
    com.bsuir.sdtt: DEBUG